#### Data source :https://archive.ics.uci.edu/ml/machine-learning-databases/00228/

In [3]:
import numpy as np
import pandas as pd
import csv
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
import os

In [4]:
folder = os.path.join(os.getcwd(), 'data' + '\\')
df = pd.DataFrame(columns=['Company','Timestamp','Label','Headline'])
for i in os.scandir(folder):
    path = folder + i.name
    a = pd.read_csv(path,sep=',',names=['Company','Timestamp','Label','Headline'],skiprows=[0])
    df = pd.concat([df,a])

FileNotFoundError: [Errno 2] No such file or directory: '/Users/LukeC/Documents/GitHub/CITS4404_proj/data\\'

In [108]:
len(df)

16964

In [72]:
df.head()

Company            Timestamp Label  \
0     ABT  2020-10-09 06:14:00     0   
1     ABT  2020-10-08 22:15:00     0   
2     ABT  2020-10-08 06:09:00     0   
3     ABT  2020-10-07 17:03:00     0   
4     ABT  2020-10-07 15:28:00     0   

                                            Headline  
0  Did You Participate In Any Of Abbott Laborator...  
1  13 Biggest Companies That Hire Felons Insider ...  
2  3 Safe Stocks to Buy in a Not-So-Safe Market M...  
3  Abbott Laboratories Says Its Rapid Coronavirus...  
4  AbbVie Is Undervalued and Offers a High Yield ...

In [120]:
list(df["Headline"])[0].split()

['Did',
 'You',
 'Participate',
 'In',
 'Any',
 'Of',
 'Abbott',
 "Laboratories'",
 '(NYSE:ABT)',
 'Fantastic',
 '185%',
 'Return',
 '?',
 'Simply',
 'Wall',
 'St.']

In [112]:
df_x=df["Headline"]
df_y=df["Label"]

In [74]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=4)

In [75]:
x_train.head()

149      Why Apple Did a 4-for-1 Stock Split Motley Fool
381    The Zacks Analyst Blog Highlights: Berkshire H...
52     Big tech blows a collective raspberry at the H...
138    Apple Readies Subscription Bundles to Boost Di...
370    INTC SHAREHOLDER DEADLINE: Bernstein Liebhard ...
Name: Headline, dtype: object

In [76]:
cv1 = CountVectorizer()

In [77]:
x_traincv= cv1.fit_transform(x_train)

In [78]:
a=x_traincv.toarray()
len(a)

13571

In [79]:
len(cv1.vocabulary_)

8131

In [80]:
a[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [81]:
cv1.inverse_transform(a[0])

[array(['apple', 'did', 'fool', 'for', 'motley', 'split', 'stock', 'why'],
       dtype='<U18')]

In [82]:
x_train.iloc[0]
x_train.head()

149      Why Apple Did a 4-for-1 Stock Split Motley Fool
381    The Zacks Analyst Blog Highlights: Berkshire H...
52     Big tech blows a collective raspberry at the H...
138    Apple Readies Subscription Bundles to Boost Di...
370    INTC SHAREHOLDER DEADLINE: Bernstein Liebhard ...
Name: Headline, dtype: object

In [83]:
x_testcv=cv1.transform(x_test)

In [84]:
x_testcv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [85]:
 mnb = MultinomialNB()
 y_train.head()

149    0
381    1
52     1
138    0
370    0
Name: Label, dtype: object

In [86]:
y_train=y_train.astype('int')

In [87]:
y_train

149    0
381    1
52     1
138    0
370    0
      ..
162    1
201    0
269    0
44     1
93     0
Name: Label, Length: 13571, dtype: int32

In [88]:
mnb.fit(x_traincv,y_train)

MultinomialNB()

In [89]:
testmessage=x_test.iloc[0]

In [90]:
predictions=mnb.predict(x_testcv)

In [91]:
predictions

array([0, 0, 0, ..., 0, 0, 0])

In [107]:
z = 0
o = 0
m = 0
for i in predictions:
    if i == 0:
        z += 1
    elif i == -1:
        m += 1
    else:
        o += 1
print(o)
print(z)
print(m)
        


640
2495
258


In [92]:
a=np.array(y_test)

In [93]:
a

array([0, -1, 0, ..., -1, 0, 1], dtype=object)

In [94]:
count=0

In [95]:
for i in range (len(predictions)):
    if predictions[i]==a[i]:
        count=count+1

In [96]:
count

2355

In [97]:
len(predictions)

3393

In [99]:
2355/3393

0.6940760389036251