In [1]:
import numpy as np
import pandas as pd
import csv
import os
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [2]:
folder = os.path.join(os.getcwd(), 'data' + '\\')
df = pd.DataFrame(columns=['Company','Timestamp','Label','Headline'])
for i in os.scandir(folder):
    path = folder + i.name
    a = pd.read_csv(path,sep=',',names=['Company','Timestamp','Label','Headline'],skiprows=[0])
    df = pd.concat([df,a])

In [3]:
len(df)

16964

In [4]:
df.head()

Company            Timestamp Label  \
0     ABT  2020-10-09 06:14:00     0   
1     ABT  2020-10-08 22:15:00     0   
2     ABT  2020-10-08 06:09:00     0   
3     ABT  2020-10-07 17:03:00     0   
4     ABT  2020-10-07 15:28:00     0   

                                            Headline  
0  Did You Participate In Any Of Abbott Laborator...  
1  13 Biggest Companies That Hire Felons Insider ...  
2  3 Safe Stocks to Buy in a Not-So-Safe Market M...  
3  Abbott Laboratories Says Its Rapid Coronavirus...  
4  AbbVie Is Undervalued and Offers a High Yield ...

In [5]:
df_x=df["Headline"]
df_y=df["Label"]

In [6]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=4)

In [7]:
x_train.head()

149      Why Apple Did a 4-for-1 Stock Split Motley Fool
381    The Zacks Analyst Blog Highlights: Berkshire H...
52     Big tech blows a collective raspberry at the H...
138    Apple Readies Subscription Bundles to Boost Di...
370    INTC SHAREHOLDER DEADLINE: Bernstein Liebhard ...
Name: Headline, dtype: object

In [8]:
cv1 = CountVectorizer()

In [9]:
x_traincv=cv1.fit_transform(x_train)

In [10]:
a=x_traincv.toarray()
len(a)

13571

In [11]:
len(cv1.vocabulary_)

8131

In [12]:
a[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [13]:
cv1.inverse_transform(a[0])

[array(['apple', 'did', 'fool', 'for', 'motley', 'split', 'stock', 'why'],
       dtype='<U18')]

In [14]:
x_train.iloc[0]
x_train.head()

149      Why Apple Did a 4-for-1 Stock Split Motley Fool
381    The Zacks Analyst Blog Highlights: Berkshire H...
52     Big tech blows a collective raspberry at the H...
138    Apple Readies Subscription Bundles to Boost Di...
370    INTC SHAREHOLDER DEADLINE: Bernstein Liebhard ...
Name: Headline, dtype: object

In [15]:
x_testcv=cv1.transform(x_test)

In [16]:
x_testcv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [17]:
 svc = SVC()
 y_train.head()

149    0
381    1
52     1
138    0
370    0
Name: Label, dtype: object

In [18]:
y_train=y_train.astype('int')

In [19]:
y_train

149    0
381    1
52     1
138    0
370    0
      ..
162    1
201    0
269    0
44     1
93     0
Name: Label, Length: 13571, dtype: int32

In [20]:
svc.fit(x_traincv,y_train)

SVC()

In [21]:
testmessage=x_test.iloc[0]

In [22]:
predictions=svc.predict(x_testcv)

In [23]:
predictions

array([ 0,  0,  0, ..., -1,  0,  0])

In [24]:
z = 0
o = 0
m = 0
for i in predictions:
    if i == 0:
        z += 1
    elif i == -1:
        m += 1
    else:
        o += 1
print(o)
print(z)
print(m)
        


421
2804
168


In [25]:
a=np.array(y_test)

In [26]:
a

array([0, -1, 0, ..., -1, 0, 1], dtype=object)

In [27]:
count=0

In [28]:
for i in range (len(predictions)):
    if predictions[i]==a[i]:
        count=count+1

In [29]:
count

2588

In [30]:
len(predictions)

3393

In [32]:
2588/3393

0.7627468317123489